# Generated by Django 3.2.8 on 2021-10-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='booked_by_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='booked_advisor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
