# Generated by Django 3.2.8 on 2021-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211028_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='booked_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='booked_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='booked_by_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='booked_advisor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
