# Generated by Django 3.2.8 on 2021-10-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_advisor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
