# Generated by Django 3.2.8 on 2021-10-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211028_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='booked_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='booked_advisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='booked_time',
        ),
    ]
